### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by tejasri19** [xdbai-source/RPNet#1]
Please provide code to reproduce the results as the paper is published.

**Comment by Nitishkr22** [comment]
@xdbai-source Share the code please.

**Comment by pardhu-nadella** [comment]
@xdbai-source Could you please share your code?

**Comment by xdbai-source** [comment]
Hi, we have shared our source codes.



***@***.***
 
From: Pardhu Nadella
Date: 2023-07-27 00:17
To: xdbai-source/RPNet
CC: xdbai; Mention
Subject: Re: [xdbai-source/RPNet] Code Release (Issue #1)
Could you please share your code.

**Comment by xdbai-source** [comment]
Hi, we have shared our source codes.




***@***.***
 
From: Tejasri Nampally
Date: 2023-07-17 18:56
To: xdbai-source/RPNet
CC: Subscribed
Subject: [xdbai-source/RPNet] Code Release (Issue #1)
Please provide code to reproduce the results as the paper is published.
